services:
  postgres:
    image: postgres:17.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./local_data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=iodine_db
