version: 0.1
registry_identifier: local_registry_01
pipelines:
  - id: pipeline_01
    description: This is a pipeline
    steps:
      - id: step_01
        description: This is a modified step
        working_directory: ./src/pipeline
        entrypoint: task_1.py
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_1.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
      - id: step_02
        description: This is a modified step
        depends_on:
          - step_01
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_2.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
      - id: step_03
        description: This is a modified step
        depends_on:
          - step_02
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_3.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
  - id: pipeline_02
    description: This is a pipeline
    steps:
      - id: step_01
        description: This is a modified step
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_1.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
      - id: step_02
        description: This is a modified step
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_2.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
      - id: step_03
        description: This is a modified step
        depends_on:
          - step_01
          - step_02
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config: !local_process
          entry_point:
            - python
            - task_3.py
          args:
            - arg1
            - arg2
          env_vars:
            - key: key
              value: value
          cpu_request: 100m
          memory_request: 100m
          timeout_seconds: 10
