version: 0.1
registry_identifier: local_registry_01
pipelines:
  - name: Pipeline 1
    description: This is a pipeline
    steps:
      - name: Step 1
        description: This is a modified step
        needs:
          - Step 2
        working_directory: ./src/pipeline
        entrypoint: task_1.py
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
      - name: Step 2
        description: This is a modified step
        needs:
          - Step 1
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
      - name: Step 3
        description: This is a modified step
        needs:
          - Step 1
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
  - name: Pipeline 2
    description: This is a pipeline
    steps:
      - name: Step 1
        description: This is a modified step
        needs:
          - Step 2
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
      - name: Step 2
        description: This is a modified step
        needs:
          - Step 1
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
      - name: Step 3
        description: This is a modified step
        needs:
          - Step 1
        working_directory: ./src/pipeline
        entrypoint: python
        environment:
          - key: key
            value: value
        labels:
          - key: key
            value: value
        executor_config:
          local_process:
            cpu_request: 100m
            memory_request: 100m
            timeout_seconds: 10
