//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use super::sea_orm_active_enums::TaskRunStatus;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "task_runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub pipeline_run_id: Uuid,
    pub task_def_id: Uuid,
    pub status: TaskRunStatus,
    pub attempts: i32,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub output_metadata: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub end_time: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pipeline_runs::Entity",
        from = "Column::PipelineRunId",
        to = "super::pipeline_runs::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PipelineRuns,
}

impl Related<super::pipeline_runs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PipelineRuns.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
