//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "task_definitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub pipeline_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config_schema: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub user_code_metadata: Option<Json>,
    pub depends_on: Option<Vec<Uuid>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pipeline_definitions::Entity",
        from = "Column::PipelineId",
        to = "super::pipeline_definitions::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PipelineDefinitions,
}

impl Related<super::pipeline_definitions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PipelineDefinitions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
