[package]
name = "iodine-pysdk"
version = "0.1.0"
edition = "2024"

[dependencies]
iodine-common = { workspace = true }

async-trait = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
